import { expect, test, type Page } from '@playwright/test'
import { collectErrors } from './console'

async function viewAs(page: Page, name: string) {
  await page.getByRole('button', { name: /^Viewing as/ }).click()
  await page.getByRole('menuitem', { name: new RegExp(name) }).click()
}

test('start from intake (1a, 2a): blocked until all four are named, then AGT-0123 is a draft', async ({ page }) => {
  const errors = collectErrors(page)
  await page.goto('/inventory')
  await viewAs(page, 'Dana')
  await page.goto('/inventory/agents/med-rec/onboarding/intake?scenario=onboarding-intake')
  await expect(page.getByText('Intake approved · not started')).toBeVisible()
  await expect(page.getByText('REQ-0093 · approved 29 Sep')).toBeVisible()
  const start = page.getByRole('button', { name: 'Start onboarding' })
  await expect(start).toHaveAttribute('aria-disabled', 'true')
  await expect(page.getByText('technical owner not set.')).toBeVisible()
  await expect(page.getByText('Marcus would directly supervise 22 agent activities.')).toBeVisible()
  await expect(page.getByRole('region', { name: 'Marcus’s span' })).toContainText('Med Rec Agent · new')

  await page.getByLabel('Technical owner').selectOption('sam')
  await expect(page.getByText('Dana · 4 of 4')).toBeVisible()
  await page.getByRole('button', { name: 'Start onboarding' }).click()
  await expect(page).toHaveURL(/\/inventory\/agents\/med-rec\/onboarding\/job$/)
  await expect(page.getByRole('button', { name: /^1 · Intake Dana · done 01 Oct/ })).toBeVisible()
  await expect(page.getByRole('button', { name: /^2 · Job description Marcus · 2 of 7/ })).toBeVisible()
  await expect(page.getByText('AGT-0123 · v0.1 · from REQ-0093')).toBeVisible()
  expect(errors).toEqual([])
})

test('Review focus 4: unknown agents and steps are Not found; later steps wait for the start', async ({ page }) => {
  const errors = collectErrors(page)
  await page.goto('/inventory/agents/nope/onboarding/job')
  await expect(page.getByRole('heading', { name: 'Page not found' })).toBeVisible()
  await page.goto('/inventory/agents/med-rec/onboarding/nope')
  await expect(page.getByRole('heading', { name: 'Page not found' })).toBeVisible()
  await page.goto('/inventory/agents/med-rec/onboarding/job?scenario=onboarding-intake')
  await expect(page.getByText('Starts when Dana starts onboarding.')).toBeVisible()
  expect(errors).toEqual([])
})

test('Review focus 5: on 01 Oct the boards hold nothing from December', async ({ page }) => {
  const errors = collectErrors(page)
  await page.goto('/operations/divisions/medications?scenario=onboarding-intake')
  await expect(page.locator('[data-row-id="renal-dosing"]')).toContainText('Within scope')
  await expect(page.locator('[data-row-id="med-rec"]')).toHaveCount(0)
  await expect(page.locator('[data-row-id="controlled-drug"]')).not.toContainText('Paused')
  await expect(page.locator('[data-row-id]')).toHaveCount(19)
  expect(errors).toEqual([])
})

test('job description (1b) from Drafts (1i): Continue lands on the first missing field', async ({ page }) => {
  const errors = collectErrors(page)
  await page.goto('/inventory?tab=drafts&scenario=onboarding-at-5-of-7')
  await expect(page.getByRole('button', { name: 'Waiting on me · 1' })).toBeVisible()
  const row = page.locator('[data-row-id="med-rec"]')
  await expect(row).toContainText('Escalation triggers, inaccuracy target')
  await expect(row).toContainText('Marcus · you')
  await expect(row).toContainText('6 of 13')
  await row.getByRole('link', { name: 'Continue' }).click()
  await expect(page).toHaveURL(/\/inventory\/agents\/med-rec\/onboarding\/job\?field=escalation$/)
  await expect(page.getByText('Welcome back, Marcus')).toBeVisible()
  await expect(page.getByRole('textbox', { name: 'Escalation trigger' })).toBeFocused()

  await page.getByRole('button', { name: '+ Patient on dialysis' }).click()
  const inaccurate = page.getByRole('textbox', { name: 'Inaccurate lines target, %' })
  await inaccurate.fill('2')
  await inaccurate.blur()
  await expect(page.getByRole('heading', { name: 'Job description · 7 of 7' })).toBeVisible()
  await expect(page.getByRole('button', { name: /^2 · Job description Marcus · done 04 Oct/ })).toBeVisible()
  expect(errors).toEqual([])
})

test('systems and verbs (1c): naming Teams · write’s activity finishes the grid', async ({ page }) => {
  const errors = collectErrors(page)
  await page.goto('/inventory/agents/med-rec/onboarding/systems?scenario=onboarding-systems')
  await expect(page.getByRole('heading', { name: 'Systems and verbs · 3 of 4' })).toBeVisible()
  await expect(page.getByText('Reads Epic, the worklist and Pyxis. Drafts in Epic. Writes to the worklist and Teams.')).toBeVisible()
  await expect(page.locator('[data-cell="changed"]')).toHaveCount(1)
  await page.getByRole('combobox', { name: 'Teams · write: the activity it serves' }).selectOption('escalation')
  await expect(page.getByRole('heading', { name: 'Systems and verbs · done' })).toBeVisible()
  await expect(page.getByRole('button', { name: /^3 · Systems and verbs Marcus · done 05 Oct/ })).toBeVisible()
  await expect(page.locator('[data-cell="changed"]')).toHaveCount(0)
  // Sign is locked for every agent: no toggle exists for it.
  await expect(page.getByRole('button', { name: 'Epic · sign' })).toHaveCount(0)
  expect(errors).toEqual([])
})

test('tools and hard stops (1d): Sam sends the tested set; Priya finds it in the inbox', async ({ page }) => {
  const errors = collectErrors(page)
  await page.goto('/inventory')
  await viewAs(page, 'Sam')
  await page.goto('/inventory/agents/med-rec/onboarding/tools?scenario=onboarding-tools-tested')
  await expect(page.getByText('Would have blocked 7 of 1,204 drafts')).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Tools and hard stops · done' })).toBeVisible()
  await expect(page.getByRole('table', { name: 'Tools' }).locator('[data-row-id]')).toHaveCount(5)
  await page.getByRole('button', { name: 'Send to Priya for approval' }).click()
  await expect(page.getByRole('button', { name: /^5 · Sponsor approval Priya · waiting since 06 Oct/ })).toBeVisible()

  await viewAs(page, 'Priya')
  await page.goto('/operations/inbox')
  await page.getByRole('link', { name: /Review: final set/ }).click()
  await page.getByRole('link', { name: 'Open the final set' }).click()
  await expect(page).toHaveURL(/\/inventory\/agents\/med-rec\/onboarding\/approval$/)
  expect(errors).toEqual([])
})

test('sponsor approval (1e–1g): Priya sends HS-11 back, Sam re-tests, Priya approves and signs', async ({ page }) => {
  const errors = collectErrors(page)
  await page.goto('/inventory')
  await viewAs(page, 'Priya')
  await page.goto('/inventory/agents/med-rec/onboarding/approval?scenario=onboarding-sponsor-review')
  await expect(page.getByText('Waiting for you since 06 Oct 15:10')).toBeVisible()
  await expect(page.getByText('First review.')).toBeVisible()
  await page.getByRole('button', { name: /HS-11 v1/ }).click()
  await page.getByRole('button', { name: 'Request changes' }).click()
  await expect(page.getByRole('button', { name: /^5 · Sponsor approval Priya · requesting changes/ })).toBeVisible()
  await expect(page.getByText('the row you selected')).toBeVisible()
  await page.getByRole('textbox', { name: 'Note for Sam' }).fill('HS-11 shows 0 blocks. Before I sign, please test it on September’s 8 East transfers.')
  await page.getByRole('button', { name: 'Send back to Sam' }).click()
  await expect(page.getByRole('button', { name: /^5 · Sponsor approval Priya · reset, opens when you send/ })).toBeVisible()

  await viewAs(page, 'Sam')
  await page.goto('/inventory/agents/med-rec/onboarding/tools')
  await expect(page.getByRole('note', { name: 'Priya sent this back' })).toContainText('September’s 8 East transfers')
  await page.getByRole('button', { name: 'Run test' }).click()
  await expect(page.getByText('Would have blocked 0 of 212')).toBeVisible()
  await page.getByRole('button', { name: 'Send to Priya again' }).click()

  await viewAs(page, 'Priya')
  await page.goto('/inventory/agents/med-rec/onboarding/approval')
  await expect(page.getByText('Review 2.')).toBeVisible()
  await page.getByRole('button', { name: 'Approve and sign' }).click()
  await expect(page).toHaveURL(/\/inventory\/agents\/med-rec\/onboarding\/review$/)
  await expect(page.getByText('AGT-0123 · v1.0 · frozen')).toBeVisible()
  expect(errors).toEqual([])
})
