function CS(){
const C={ink:'oklch(0.21 0.004 90)',t2:'oklch(0.41 0.006 90)',meta:'oklch(0.5 0.006 90)',line:'oklch(0.925 0.004 90)',ls:'oklch(0.87 0.005 90)',sel:'oklch(0.965 0.003 90)',page:'oklch(0.985 0.002 90)',icon:'oklch(0.6 0.006 90)',off:'oklch(0.72 0.006 90)',str:'oklch(0.31 0.005 90)',w:'oklch(1 0 0)',acc:'oklch(0.43 0.15 268)',tint:'oklch(0.96 0.02 268)',rev:'oklch(0.5 0.085 200)',hover:'oklch(0.975 0.003 90)',warn:'oklch(0.65 0.14 70)',warnT:'oklch(0.5 0.1 62)',crit:'oklch(0.52 0.19 27)',canvas:'oklch(0.93 0.003 90)'};
const F="'IBM Plex Sans',sans-serif", M="'IBM Plex Mono',monospace";
const svg=(s,inner)=>`<svg width="${s}" height="${s}" viewBox="0 0 12 12" style="flex:none;">${inner}</svg>`;
const check=(s=12,c=C.meta)=>svg(s,`<path d="M2.5 6.2l2.3 2.3 4.7-5" fill="none" stroke="${c}" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"></path>`);
const box=(s=12,c=C.ink)=>`<span style="flex:none; width:${s}px; height:${s}px; box-sizing:border-box; border:1.5px solid ${c}; border-radius:2px;"></span>`;
const lock=(c=C.meta)=>svg(12,`<path d="M3.5 5.5V4a2.5 2.5 0 0 1 5 0v1.5" fill="none" stroke="${c}" stroke-width="1.4"></path><rect x="2" y="5.5" width="8" height="5.5" rx="1" fill="${c}"></rect>`);
const RING='M6 1.75a4.25 4.25 0 1 1 0 8.5a4.25 4.25 0 1 1 0-8.5Z';
const mark=(st,s=12)=>({review:svg(s,`<path d="${RING}" fill="none" stroke="${C.rev}" stroke-width="1.5"></path>`),warn:svg(s,`<path d="M6 0.9L11.1 6L6 11.1L0.9 6Z" fill="${C.warn}"></path>`),crit:svg(s,`<path d="M6 1.2L11.4 10.6H0.6Z" fill="${C.crit}"></path>`),stale:svg(s,`<path d="${RING}" fill="none" stroke="${C.meta}" stroke-width="1.5" stroke-dasharray="2.2 1.75"></path>`),shadow:svg(s,`<path d="${RING}" fill="none" stroke="${C.icon}" stroke-width="1.5"></path><path d="M6 1.75a4.25 4.25 0 0 0 0 8.5Z" fill="${C.icon}"></path>`),paused:svg(s,`<path d="M2.6 2h2.4v8H2.6ZM7 2h2.4v8H7Z" fill="${C.icon}"></path>`)}[st]||'');
const TC={review:C.rev,warn:C.warnT,crit:C.crit,stale:C.str,shadow:C.meta,paused:C.meta}, BC={review:C.rev,warn:C.warn,crit:C.crit,stale:C.icon,shadow:C.ls,paused:C.ls};
const chip=(st,t,sm=true)=>st==='normal'?`<span style="font-size:${sm?13:14}px; line-height:${sm?18:20}px; color:${C.meta}; white-space:nowrap;">${t}</span>`:`<span style="display:inline-flex; align-items:center; gap:6px; align-self:flex-start; justify-self:start; height:${sm?22:24}px; box-sizing:border-box; padding:0 ${sm?7:8}px 0 6px; border:1px ${st==='stale'?'dashed':'solid'} ${BC[st]}; border-radius:2px; white-space:nowrap;">${mark(st)}<span style="font-size:${sm?13:14}px; line-height:${sm?18:20}px; font-weight:${['review','warn','crit','stale'].includes(st)?600:400}; color:${TC[st]};">${t}</span></span>`;
const mono=`font-family:${M}; font-size:12px; line-height:16px; color:${C.meta};`;
const LBL=`font-family:${M}; font-size:12px; line-height:16px; font-weight:600; text-transform:uppercase; letter-spacing:0.05em; color:${C.meta};`;
const tag=t=>`<span style="font-family:${M}; font-size:12px; line-height:16px; color:${C.t2}; box-shadow:inset 0 0 0 1px ${C.ls}; border-radius:2px; padding:1px 5px; white-space:nowrap;">${t}</span>`;
const u=t=>`<span style="text-decoration:underline; text-underline-offset:3px;">${t}</span>`;
const B=`display:inline-flex; align-items:center; justify-content:center; gap:8px; height:36px; padding:0 14px; border-radius:3px; font-family:${F}; font-size:14px; font-weight:600; white-space:nowrap; cursor:pointer; flex:none;`;
const chev=`<svg width="10" height="10" viewBox="0 0 10 10" style="flex:none;"><path d="M2 3.5l3 3 3-3" fill="none" stroke="currentColor" stroke-width="1.5"></path></svg>`;
const primary=(t,h=36)=>`<button style="${B} height:${h}px; border:none; background:${C.acc}; color:${C.w};">${t}</button>`;
const secondary=(t,h=36)=>`<button style="${B} height:${h}px; border:1px solid ${C.ls}; background:${C.w}; color:${C.ink};">${t}</button>`;
const ghost=(t,h=32)=>`<button style="${B} height:${h}px; padding:0 8px; border:none; background:transparent; color:${C.t2};">${t}</button>`;
const blocked=(t,h=36)=>`<button style="${B} height:${h}px; border:1px solid ${C.line}; background:${C.sel}; color:${C.meta}; cursor:not-allowed;">${t}</button>`;
const pill=(t,on)=>`<span style="display:inline-flex; align-items:center; height:32px; box-sizing:border-box; padding:0 12px; border:1px solid ${on?C.ink:C.ls}; border-radius:3px; font-size:14px; white-space:nowrap;${on?' font-weight:600;':` color:${C.t2};`}">${t}</span>`;
const NAV=['Portfolio','Inventory','Operations','Reports','Settings'];
const nav=(av,act)=>`<div style="height:48px; box-sizing:border-box; display:flex; align-items:center; justify-content:space-between; padding:0 24px; background:${C.w}; border-bottom:1px solid ${C.line};"><div style="display:flex; align-items:center; gap:32px; height:100%;"><span style="font-size:14px; font-weight:600; letter-spacing:0.04em;">AIMS</span><div style="display:flex; align-items:stretch; gap:24px; height:100%; font-size:14px;">${NAV.map(n=>n===act?`<span style="display:flex; align-items:center; font-weight:600; box-shadow:inset 0 -2px 0 ${C.acc};">${n}</span>`:`<span style="display:flex; align-items:center; color:${C.t2};">${n}</span>`).join('')}</div></div><div style="display:flex; align-items:center; gap:14px; font-size:14px; color:${C.t2};"><span>Lakeshore Health</span><span style="width:28px; height:28px; border-radius:50%; background:${C.sel}; display:flex; align-items:center; justify-content:center; font-size:12px; font-weight:600; color:${C.ink};">${av}</span></div></div>`;
const frame=(av,act,inner)=>`<div style="position:relative; width:1440px; background:${C.page}; border:1px solid ${C.ls}; border-radius:8px; overflow:hidden; font-family:${F}; color:${C.ink};">${nav(av,act)}${inner}</div>`;
const tabs=(items,act)=>`<div style="display:flex; align-items:stretch; gap:24px; height:40px;">${items.map(t=>`<span style="display:flex; align-items:center; padding:0 2px; font-size:14px; white-space:nowrap;${t===act?` font-weight:600; box-shadow:inset 0 -2px 0 ${C.acc};`:` color:${C.t2};`}">${t}</span>`).join('')}</div>`;
const stepCell=([mk,label,sub,muted],active)=>`<div style="display:flex; flex-direction:column; gap:2px; padding:12px 16px 14px;${active?` background:${C.tint}; box-shadow:inset 0 -2px 0 ${C.acc};`:''}"><span style="display:flex; align-items:center; gap:6px; font-size:14px; line-height:20px;${active?' font-weight:600;':''}${muted?` color:${C.meta};`:''}">${mk||''} ${label}</span><span style="font-size:12px; line-height:16px; color:${C.meta};">${sub}</span></div>`;
const head=o=>{const low=o.tabs||o.steps;return `<div style="display:flex; flex-direction:column; gap:${low?16:0}px; padding:24px 40px ${low?0:24}px; background:${C.w}; border-bottom:1px solid ${C.line};"><div style="display:flex; align-items:flex-end; justify-content:space-between; gap:24px;"><div style="display:flex; flex-direction:column; gap:6px; min-width:0;"><span style="font-size:12px; line-height:16px; color:${C.meta};">${o.crumb}</span><span style="display:flex; align-items:center; gap:12px; flex-wrap:wrap;"><span style="font-size:24px; line-height:32px; font-weight:600;">${o.title}</span>${o.status?`<span style="font-size:14px; color:${C.meta};">${o.status}</span>`:''}${o.ids?`<span style="${mono}">${o.ids}</span>`:''}${o.chips||''}</span>${o.people?`<span style="display:flex; gap:20px; flex-wrap:wrap; font-size:14px; line-height:20px; color:${C.meta};">${o.people.map(([a,b])=>`<span>${a} <span style="color:${C.ink};">${b}</span></span>`).join('')}</span>`:''}${o.sub?`<span style="font-size:14px; line-height:20px; color:${C.t2}; max-width:900px; text-wrap:pretty;">${o.sub}</span>`:''}</div><div style="display:flex; align-items:center; gap:12px; flex:none;">${o.right||''}</div></div>${o.steps?`<div style="display:grid; grid-template-columns:repeat(${o.steps.length},minmax(0,1fr));">${o.steps.map((s,i)=>stepCell(s,i===o.active)).join('')}</div>`:''}${o.tabs?tabs(o.tabs,o.tab):''}</div>`;};
const PEOPLE=[['Program lead','Dana'],['Owner','Marcus'],['Technical owner','Sam'],['Sponsor','Priya'],['Division','Medications']];
const split=(main,side,sw=340,gap=40,pad='32px 40px 48px')=>`<div style="display:grid; grid-template-columns:minmax(0,1fr) ${sw}px; column-gap:${gap}px; align-items:start; padding:${pad};">${main}${side}</div>`;
const splitL=(side,main,sw=420,gap=24,pad='24px 40px 48px')=>`<div style="display:grid; grid-template-columns:${sw}px minmax(0,1fr); column-gap:${gap}px; align-items:start; padding:${pad};">${side}${main}</div>`;
const body=(inner,gap=20,pad='28px 40px 48px')=>`<div style="display:flex; flex-direction:column; gap:${gap}px; padding:${pad};">${inner}</div>`;
const paper=(inner,gap=28)=>`<div style="display:flex; flex-direction:column; gap:${gap}px; padding:28px 32px 32px; background:${C.w}; border:1px solid ${C.ls}; border-radius:6px; min-width:0;">${inner}</div>`;
const card=(inner,extra='')=>`<div style="display:flex; flex-direction:column; background:${C.w}; border:1px solid ${C.line}; border-radius:6px; overflow:hidden; min-width:0;${extra}">${inner}</div>`;
const col=(inner,gap=16,extra='')=>`<div style="display:flex; flex-direction:column; gap:${gap}px; min-width:0;${extra}">${inner}</div>`;
const row=(inner,gap=12,extra='')=>`<div style="display:flex; align-items:center; gap:${gap}px; flex-wrap:wrap;${extra}">${inner}</div>`;
const between=(a,b,extra='')=>`<div style="display:flex; align-items:center; justify-content:space-between; gap:16px;${extra}">${a}${b}</div>`;
const secHead=(n,t,d,r='')=>`<div style="display:flex; align-items:baseline; justify-content:space-between; gap:16px;"><span style="display:flex; flex-direction:column; gap:4px;"><span style="display:flex; align-items:baseline; gap:12px;">${n?`<span style="${mono}">${n}</span>`:''}<span style="font-size:18px; line-height:24px; font-weight:600;">${t}</span></span>${d?`<span style="font-size:16px; line-height:24px; color:${C.t2}; text-wrap:pretty; max-width:760px;">${d}</span>`:''}</span><span style="flex:none; font-size:14px; color:${C.meta};">${r}</span></div>`;
const group=(label,inner,gap=10,right='')=>`<div style="display:flex; flex-direction:column; gap:${gap}px; min-width:0;"><div style="display:flex; align-items:baseline; justify-content:space-between; gap:12px;"><span style="${LBL}">${label}</span>${right?`<span style="font-size:13px; line-height:18px; color:${C.meta};">${right}</span>`:''}</div>${inner}</div>`;
const dl=(rows,w=160)=>rows.map(([k,v],i)=>`<div style="display:grid; grid-template-columns:${w}px minmax(0,1fr); column-gap:20px; align-items:baseline; padding:12px 0;${i?` border-top:1px solid ${C.line};`:''}"><span style="font-size:14px; line-height:24px; color:${C.meta};">${k}</span><div style="display:flex; flex-direction:column; gap:4px; font-size:16px; line-height:24px; text-wrap:pretty; min-width:0;">${v}</div></div>`).join('');
const li=(t,r)=>`<span style="display:flex; align-items:baseline; justify-content:space-between; gap:12px;"><span>${t}</span><span style="flex:none; font-size:14px; color:${C.meta};">${r}</span></span>`;
const sideHead=(t,s,p)=>`<div style="display:flex; flex-direction:column; gap:2px; padding:16px 20px;"><span style="font-size:16px; line-height:24px; font-weight:600;">${t}</span>${s?`<span style="font-size:14px; line-height:20px; color:${C.meta}; text-wrap:pretty;">${s}</span>`:''}</div>${p!==undefined?`<div style="height:4px; margin:0 20px 8px; background:${C.line}; border-radius:2px;"><div style="width:${p}%; height:4px; background:${C.t2}; border-radius:2px;"></div></div>`:''}`;
const sRow=(mk,t,r='',o={})=>`<div style="display:grid; grid-template-columns:${mk?'12px ':''}minmax(0,1fr) auto; column-gap:10px; align-items:center; min-height:36px; padding:${o.pad||'0'} 20px; font-size:14px; line-height:20px; color:${o.sel||o.strong?C.ink:C.t2};${o.sel?` background:${C.tint}; box-shadow:inset 2px 0 0 ${C.acc}; font-weight:600;`:''}">${mk||''}<span style="min-width:0;">${t}</span><span style="font-size:12px; font-weight:400; color:${C.meta}; text-align:right;">${r}</span></div>`;
const sBlock=(inner,top=true)=>`<div style="display:flex; flex-direction:column; gap:10px; padding:16px 20px 20px;${top?` border-top:1px solid ${C.line};`:''}">${inner}</div>`;
const side=inner=>card(inner);
const note=(b,t)=>`<span style="font-size:14px; line-height:20px; color:${C.t2}; text-wrap:pretty;">${b?`<span style="font-weight:600; color:${C.ink};">${b}</span> `:''}${t}</span>`;
const small=t=>`<span style="font-size:14px; line-height:20px; color:${C.meta}; text-wrap:pretty;">${t}</span>`;
const fieldBox=(t,o={})=>`<div style="min-height:44px; box-sizing:border-box; padding:10px 14px; background:${o.locked?C.sel:C.w}; border:1px solid ${o.locked?C.line:C.ls}; border-radius:3px; font-size:16px; line-height:24px; display:flex; align-items:center; justify-content:space-between; gap:12px;${o.focus?` outline:2px solid ${C.ink}; outline-offset:1px;`:''}${o.muted?` color:${C.meta};`:''}"><span>${t}${o.focus&&o.caret!==false?`<span style="display:inline-block; width:1.5px; height:18px; margin-left:2px; vertical-align:-3px; background:${C.ink};"></span>`:''}</span>${o.locked?lock():o.plain?'':`<span style="color:${C.meta}; display:flex;">${chev}</span>`}</div>`;
const textarea=(t,o={})=>`<div style="min-height:${o.h||108}px; box-sizing:border-box; padding:10px 14px; background:${C.w}; border:1px solid ${C.ls}; border-radius:3px; font-size:16px; line-height:24px; text-wrap:pretty;${o.focus?` outline:2px solid ${C.ink}; outline-offset:1px;`:''}${o.muted?` color:${C.meta};`:''}">${t}${o.focus?`<span style="display:inline-block; width:1.5px; height:18px; margin-left:2px; vertical-align:-3px; background:${C.ink};"></span>`:''}</div>`;
const field=(label,right,ctrl,help)=>`<div style="display:flex; flex-direction:column; gap:8px; min-width:0;"><div style="display:flex; align-items:baseline; justify-content:space-between; gap:16px;"><span style="font-size:14px; line-height:20px; font-weight:600;">${label}</span><span style="font-size:14px; line-height:20px; color:${C.meta};">${right||''}</span></div>${help?`<span style="font-size:14px; line-height:20px; color:${C.meta}; text-wrap:pretty;">${help}</span>`:''}${ctrl}</div>`;
const radio=(t,s,on,o={})=>`<div style="display:grid; grid-template-columns:18px minmax(0,1fr); column-gap:10px; align-items:start; padding:10px 12px; border:${on?`1.5px solid ${C.acc}`:`1px solid ${C.ls}`}; border-radius:3px; background:${on?C.tint:C.w};${o.dis?` color:${C.off};`:''}"><span style="width:18px; height:18px; margin-top:3px; box-sizing:border-box; border-radius:50%; border:1.5px solid ${on?C.acc:C.icon}; display:flex; align-items:center; justify-content:center;">${on?`<span style="width:8px; height:8px; border-radius:50%; background:${C.acc};"></span>`:''}</span><span style="display:flex; flex-direction:column;"><span style="font-size:16px; line-height:24px;${on?' font-weight:600;':''}">${t}</span>${s?`<span style="font-size:14px; line-height:20px; color:${o.dis?C.off:C.meta}; text-wrap:pretty;">${s}</span>`:''}</span></div>`;
const checkbox=(t,s,on)=>`<div style="display:grid; grid-template-columns:18px minmax(0,1fr); column-gap:10px; align-items:start;"><span style="width:18px; height:18px; margin-top:3px; box-sizing:border-box; border-radius:3px; ${on?`background:${C.acc};`:`border:1.5px solid ${C.icon};`} display:flex; align-items:center; justify-content:center;">${on?check(11,C.w):''}</span><span style="display:flex; flex-direction:column;"><span style="font-size:16px; line-height:24px;">${t}</span>${s?`<span style="font-size:14px; line-height:20px; color:${C.meta}; text-wrap:pretty;">${s}</span>`:''}</span></div>`;
const seg=(items,sel)=>`<div style="display:grid; grid-template-columns:repeat(${items.length},minmax(0,1fr)); gap:8px;">${items.map((it,i)=>{const [t,s]=Array.isArray(it)?it:[it,''];const on=i===sel;return `<div style="display:flex; flex-direction:column; gap:2px; padding:10px 14px; border-radius:3px; background:${on?C.tint:C.w}; border:${on?`1.5px solid ${C.acc}`:`1px solid ${C.ls}`};"><span style="font-size:14px; line-height:20px; font-weight:${on?600:400};">${t}</span>${s?`<span style="font-size:12px; line-height:16px; color:${C.meta};">${s}</span>`:''}</div>`;}).join('')}</div>`;
const bar=(p,w=56,c=C.t2)=>`<span style="display:inline-block; flex:none; width:${w}px; height:4px; background:${C.line}; border-radius:2px;"><span style="display:block; width:${p}%; height:4px; background:${c}; border-radius:2px;"></span></span>`;
const spark=(pts,o={})=>{const w=o.w||72,h=o.h||20,mx=Math.max(...pts),mn=Math.min(...pts),r=mx-mn||1;const d=pts.map((v,i)=>`${(i/(pts.length-1)*w).toFixed(1)},${(h-2-(v-mn)/r*(h-4)).toFixed(1)}`).join(' ');return `<svg width="${w}" height="${h}" viewBox="0 0 ${w} ${h}" style="flex:none;"><polyline points="${d}" fill="none" stroke="${o.c||C.t2}" stroke-width="1.5" stroke-linejoin="round" stroke-linecap="round"></polyline></svg>`;};
const cellWrap=x=>{const r=typeof x==='string'&&x.startsWith('>');return `<div style="min-width:0; display:flex; flex-direction:column; gap:2px;${r?' align-items:flex-end; text-align:right;':''}">${r?x.slice(1):x}</div>`;};
const table=(cols,heads,rows,o={})=>{const pad=o.pad||16,fs=o.dense===false?'14px; line-height:20px':'13px; line-height:18px';return card(`${heads?`<div style="display:grid; grid-template-columns:${cols}; column-gap:16px; align-items:center; height:32px; padding:0 ${pad}px; background:${C.page};">${heads.map(h=>`<span style="${LBL}${h.startsWith('>')?' text-align:right;':''} white-space:nowrap;">${h.replace(/^>/,'')}</span>`).join('')}</div>`:''}${rows.map((r,i)=>{const x=Array.isArray(r)?{c:r}:r;return `<div style="display:grid; grid-template-columns:${cols}; column-gap:16px; align-items:center; min-height:${x.h||o.h||44}px; padding:6px ${pad}px;${heads||i?` border-top:1px solid ${C.line};`:''} font-size:${fs};${x.sel?` background:${C.tint}; box-shadow:inset 2px 0 0 ${C.acc};`:x.hover?` background:${C.hover};`:''}${x.muted?` color:${C.meta};`:''}">${x.c.map(cellWrap).join('')}</div>`;}).join('')}`,o.extra||'');};
const l2=(a,b,bold)=>`<span style="font-size:14px; line-height:20px;${bold?' font-weight:600;':''}">${a}</span>${b?`<span style="font-size:12px; line-height:16px; color:${C.meta};">${b}</span>`:''}`;
const notice=(mk,b,t,actions='')=>`<div style="display:grid; grid-template-columns:12px minmax(0,1fr); column-gap:10px; align-items:start; padding:12px 14px; background:${C.page}; border:1px solid ${C.ls}; border-radius:3px;"><span style="display:flex; height:20px; align-items:center;">${mk}</span><div style="display:flex; flex-direction:column; gap:6px; min-width:0;"><span style="font-size:14px; line-height:20px; color:${C.t2}; text-wrap:pretty;"><span style="font-weight:600; color:${C.ink};">${b}</span> ${t}</span>${actions?`<div style="display:flex; gap:4px; margin-left:-8px;">${actions}</div>`:''}</div></div>`;
const menu=(items,w=280)=>`<div style="width:${w}px; display:flex; flex-direction:column; padding:4px 0; background:${C.w}; border:1px solid ${C.ls}; border-radius:3px; box-shadow:0 8px 24px oklch(0.21 0.004 90 / 0.14);">${items.map(it=>{if(it==='---')return `<div style="height:1px; margin:4px 0; background:${C.line};"></div>`;if(typeof it==='string')return `<div style="padding:8px 14px 4px; ${LBL}">${it}</div>`;const [t,s,o={}]=it;return `<div style="display:flex; flex-direction:column; gap:2px; padding:8px 14px;${o.sel?` background:${C.tint}; box-shadow:inset 2px 0 0 ${C.acc};`:''}"><span style="display:flex; align-items:center; justify-content:space-between; gap:8px; font-size:14px; line-height:20px;${o.sel?' font-weight:600;':''}${o.dis?` color:${C.off};`:''}">${t}${o.dis?lock(C.off):''}</span>${s?`<span style="font-size:12px; line-height:16px; color:${o.dis?C.off:C.meta};">${s}</span>`:''}</div>`;}).join('')}</div>`;
const modal=(inner,o={})=>`<div style="position:absolute; inset:0; background:oklch(0.21 0.004 90 / 0.32);"></div><div style="position:absolute; top:${o.top||96}px; left:50%; transform:translateX(-50%); width:${o.w||600}px; display:flex; flex-direction:column; background:${C.w}; border:1px solid ${C.ls}; border-radius:6px; box-shadow:0 16px 48px oklch(0.21 0.004 90 / 0.2); overflow:hidden;">${inner}</div>`;
const mHead=(t,s)=>`<div style="display:flex; flex-direction:column; gap:4px; padding:20px 24px 16px;"><span style="font-size:18px; line-height:24px; font-weight:600;">${t}</span>${s?`<span style="font-size:14px; line-height:20px; color:${C.t2}; text-wrap:pretty;">${s}</span>`:''}</div>`;
const mBody=inner=>`<div style="display:flex; flex-direction:column; gap:20px; padding:4px 24px 24px;">${inner}</div>`;
const mFoot=(l,r)=>`<div style="display:flex; align-items:center; justify-content:space-between; gap:16px; padding:14px 24px; background:${C.page}; border-top:1px solid ${C.line};"><span style="${mono}">${l||''}</span><span style="display:flex; gap:10px;">${r}</span></div>`;
const logRow=(t,a,b)=>`<div style="display:grid; grid-template-columns:64px minmax(0,1fr); column-gap:12px; padding:8px 20px; font-size:14px; line-height:20px;"><span style="${mono} line-height:20px;">${t}</span><span style="display:flex; flex-direction:column; gap:2px;"><span>${a}</span>${b?`<span style="font-size:13px; line-height:18px; color:${C.meta}; text-wrap:pretty;">${b}</span>`:''}</span></div>`;
const stat=(label,val,sub,o={})=>`<div style="display:flex; flex-direction:column; gap:2px; padding:14px 16px; min-width:0;${o.left?` border-left:1px solid ${C.line};`:''}"><span style="font-size:13px; line-height:18px; color:${C.meta};">${label}</span><span style="font-size:20px; line-height:28px; font-weight:600;">${val}</span>${sub?`<span style="font-size:12px; line-height:16px; color:${C.meta};">${sub}</span>`:''}</div>`;
const stats=items=>card(`<div style="display:grid; grid-template-columns:repeat(${items.length},minmax(0,1fr));">${items.map((s,i)=>stat(s[0],s[1],s[2],{left:i>0})).join('')}</div>`);
const S={done:check(14,C.t2),todo:box(14,C.t2),lock:`<span style="flex:none; display:inline-flex;">${lock()}</span>`,rev:mark('review',14)};
const EPICS=[['E1','Onboard an agent','E1 Onboarding Countersign'],['E2','Humans and review','E2 Humans and Review'],['E3','Shadow and go live','E3 Shadow and Go Live'],['E4','Command Board','E4 Command Board'],['E5','Exception inbox','E5 Exception Inbox'],['E6','Stop and resume','E6 Stop and Resume'],['E7','Replay and audit','E7 Replay and Audit'],['E8','Divisions and access','E8 Divisions and Access'],['E9','Changes and unregistered','E9 Changes and Unregistered'],['E10','Clinician feedback','E10 Clinician Feedback'],['E11','Reviewer behaviour','E11 Reviewer Behaviour'],['E12','RUAIH evidence','E12 RUAIH Evidence'],['E13','Review levels','E13 Review Levels'],['E14','Promote to Supervised','E14 Promote to Supervised'],['E15','Step down automatically','E15 Step Down']];
const epicNav=cur=>`<div style="display:flex; flex-wrap:wrap; gap:6px;">${EPICS.map(([id,t,f])=>id===cur?`<span style="display:inline-flex; align-items:center; height:28px; padding:0 10px; background:${C.ink}; color:${C.w}; border-radius:3px; font-size:13px; font-weight:600;">${id} · ${t}</span>`:`<a href="./${encodeURI(f)}.dc.html" style="display:inline-flex; align-items:center; height:28px; padding:0 10px; border:1px solid ${C.ls}; border-radius:3px; font-size:13px; color:${C.t2}; text-decoration:none; background:${C.w};">${id} · ${t}</a>`).join('')}</div>`;
const badge=id=>`<a href="#${id}" style="font:600 11px ui-monospace,Menlo,monospace; padding:3px 7px; background:${C.ls}; color:${C.ink}; border-radius:3px; text-decoration:none;">${id}</a>`;
const opt=(id,code,title,sub,inner)=>`<div id="${id}" style="flex:none; display:flex; flex-direction:column; gap:10px; scroll-margin-top:16px;"><div style="display:flex; align-items:baseline; gap:8px; font-size:13px; color:${C.t2};">${badge(id)}<span style="font-family:${M}; font-size:12px; color:${C.meta};">${code}</span><span style="font-size:15px; font-weight:600; color:${C.ink};">${title}</span><span>${sub}</span></div>${inner}</div>`;
const doc=o=>{const tpl=`<helmet>
<meta name="design_doc_mode" content="canvas">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@400;600&amp;family=IBM+Plex+Mono:wght@400;600&amp;display=swap">
<style>html{background:${C.canvas}}body{margin:0;background:${C.canvas};-webkit-font-smoothing:antialiased}a{color:${C.ink}}a:hover{color:${C.t2}}button{font:inherit}</style>
</helmet>
<section id="t1" style="padding:48px; display:flex; flex-direction:column; gap:28px; font-family:${F}; font-variant-numeric:tabular-nums; color:${C.ink}; width:max-content; box-sizing:border-box; background:${C.canvas};">
<div style="display:flex; flex-direction:column; gap:12px; max-width:1200px;">${epicNav(o.epic)}<div style="display:flex; align-items:baseline; gap:10px; padding-top:8px;"><a href="#t1" style="font:600 11px ui-monospace,Menlo,monospace; padding:3px 7px; background:${C.ink}; color:${C.w}; border-radius:3px; text-decoration:none;">1</a><span style="font-size:15px; font-weight:600;">${o.title}</span></div><p style="margin:0; font-size:14px; line-height:22px; color:${C.t2}; text-wrap:pretty;">${o.intro}</p></div>
<div style="display:grid; grid-template-columns:repeat(2,1440px); gap:56px 48px; align-items:start;">
${o.body}
</div>
${o.tryNext?`<p style="margin:0; font-size:13px; line-height:20px; color:${C.t2};">Try next: ${o.tryNext}</p>`:''}
</section>`;return `<!DOCTYPE html>\n<html>\n<head>\n<meta charset="utf-8">\n<meta name="viewport" content="width=device-width, initial-scale=1">\n<script src="./support.js"></script>\n</head>\n<body>\n<x-dc>\n${tpl}\n</x-dc>\n${o.logic?`<script type="text/x-dc" data-dc-script>\n${o.logic}</script>\n`:''}</body>\n</html>\n`;};
return {C,F,M,svg,check,box,lock,mark,chip,mono,LBL,tag,u,B,chev,primary,secondary,ghost,blocked,pill,nav,frame,tabs,head,PEOPLE,split,splitL,body,paper,card,col,row,between,secHead,group,dl,li,sideHead,sRow,sBlock,side,note,small,fieldBox,textarea,field,radio,checkbox,seg,bar,spark,table,l2,notice,menu,modal,mHead,mBody,mFoot,logRow,stat,stats,S,epicNav,badge,opt,doc};
}